// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDECommonData : IGDEData
    {
        private static string world_countKey = "world_count";
		private int _world_count;
        public int world_count
        {
            get { return _world_count; }
            set {
                if (_world_count != value)
                {
                    _world_count = value;
                    GDEDataManager.SetInt(_key+"_"+world_countKey, _world_count);
                }
            }
        }

        private static string versionKey = "version";
		private string _version;
        public string version
        {
            get { return _version; }
            set {
                if (_version != value)
                {
                    _version = value;
                    GDEDataManager.SetString(_key+"_"+versionKey, _version);
                }
            }
        }

        private static string auto_selected_stage_idKey = "auto_selected_stage_id";
		private string _auto_selected_stage_id;
        public string auto_selected_stage_id
        {
            get { return _auto_selected_stage_id; }
            set {
                if (_auto_selected_stage_id != value)
                {
                    _auto_selected_stage_id = value;
                    GDEDataManager.SetString(_key+"_"+auto_selected_stage_idKey, _auto_selected_stage_id);
                }
            }
        }

        private static string stageKey = "stage";
		public List<GDEStageData>      stage;
		public void Set_stage()
        {
	        GDEDataManager.SetCustomList(_key+"_"+stageKey, stage);
		}
		

        public GDECommonData()
		{
			_key = string.Empty;
		}

		public GDECommonData(string key)
		{
			_key = key;
		}
		
        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetInt(world_countKey, out _world_count);
                dict.TryGetString(versionKey, out _version);
                dict.TryGetString(auto_selected_stage_idKey, out _auto_selected_stage_id);

                dict.TryGetCustomList(stageKey, out stage);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _world_count = GDEDataManager.GetInt(_key+"_"+world_countKey, _world_count);
            _version = GDEDataManager.GetString(_key+"_"+versionKey, _version);
            _auto_selected_stage_id = GDEDataManager.GetString(_key+"_"+auto_selected_stage_idKey, _auto_selected_stage_id);

            stage = GDEDataManager.GetCustomList(_key+"_"+stageKey, stage);
         }

        public void Reset_world_count()
        {
            GDEDataManager.ResetToDefault(_key, world_countKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(world_countKey, out _world_count);
        }

        public void Reset_version()
        {
            GDEDataManager.ResetToDefault(_key, versionKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(versionKey, out _version);
        }

        public void Reset_auto_selected_stage_id()
        {
            GDEDataManager.ResetToDefault(_key, auto_selected_stage_idKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(auto_selected_stage_idKey, out _auto_selected_stage_id);
        }

        public void Reset_stage()
		{
			GDEDataManager.ResetToDefault(_key, stageKey);

			Dictionary<string, object> dict;
			GDEDataManager.Get(_key, out dict);

			dict.TryGetCustomList(stageKey, out stage);
			stage = GDEDataManager.GetCustomList(_key+"_"+stageKey, stage);

			stage.ForEach(x => x.ResetAll());
		}

        public void ResetAll()
        {
            GDEDataManager.ResetToDefault(_key, versionKey);
            GDEDataManager.ResetToDefault(_key, world_countKey);
            GDEDataManager.ResetToDefault(_key, stageKey);
            GDEDataManager.ResetToDefault(_key, auto_selected_stage_idKey);

            Reset_stage();

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
