// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEItemKeys
    {
        public static string Common_common = "common";
        public static string Stage_stage_01_01 = "stage_01_01";
        public static string Stage_stage_01_02 = "stage_01_02";
        public static string Stage_stage_01_03 = "stage_01_03";
        public static string Stage_stage_01_04 = "stage_01_04";
    }
}
